config/routes.rb
Rails.application.routes.draw do
  get 'site/index'


  resources :campaigns, only: [:new, :index, :create, :show, :update, :index] do
    get 'activation', on: :member
    get 'activate', on: :member
    get 'deactivate', on: :member

    resources :bigscreen, only: [:index]

    resources :suggestion, only: [:create, :new] do
      put 'approve', on: :member
      put 'reject', on: :member

      get "/approve" => 'suggestion#approve', as: 'approve'
      get "/reject" => 'suggestion#reject', as: 'reject'
    end

  get "/voting" => 'suggestion#new', as: 'voting'
  get "/moderate" => 'moderate#show', as: 'moderate'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'campaigns#index'
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
	belongs_to :campaign

  before_create :set_creation_approval

  scope :initial,       -> { where( initial: true ) }
  scope :approved,      -> { where( approval_status: 'APPROVED' ) }
  scope :pending,       -> { where( approval_status: 'PENDING' ) }
  scope :rejected,      -> { where( approval_status: 'REJECTED') }
  scope :not_archived,  -> { where( archived: false ) }
  scope :archived,      -> { where( archived: true ) }
  scope :sort,          -> { order( votes: :desc, updated_at: :asc ) }
  scope :not_current,   -> { where( current: false ) }
  scope :current,       -> { where( current: true ) }

  default_scope { order(votes: :desc, updated_at: :asc) } 

  class << self
    def approved_not_archived
      approved.not_archived.not_current
    end

    def rejected_not_archived
      rejected.not_archived.not_current
    end

    def pending_not_archived
      pending.not_archived.not_current
    end

    def most_voted
      not_archived.not_current.limit(1) 
    end
  end

  def set_creation_approval
    # Campaign creators make initial suggestions, approve by default
    self.approval_status = "APPROVED" if initial
    self.approval_status ||= campaign.approve_suggestions ? "PENDING" : "APPROVED"
  end

  def updated_at_as_integer
    updated_at.to_i
  end

  def make_current
    self.current = true
    self.made_current_at = Time.now
  end

  def approve
    self.approval_status = "APPROVED"
  end

  def reject
    self.approval_status = "REJECTED"
  end

  def pending
    self.approval_status = "PENDING"
  end

  def archive
    self.archived = true
    self.current = false
    self.made_current_at = nil
  end


end

app/controllers/suggestion_controller.rb
require 'digest'

class SuggestionController < ApplicationController
  layout "voting"

  before_action :get_campaign

  def create
    @suggestion = Suggestion.new(suggestion_params)
    @suggestion.campaign = @campaign

    rank = Suggestion.where(campaign_id: @campaign.id).count

    @suggestion.save()

    if @campaign.approve_suggestions
      ModerateController.test(@campaign, @suggestion)
    else
      ApprovedSuggestionJob.perform_later(campaign_id, rank, @suggestion.id)
    end

    respond_to do |format|
      format.js { head :ok } 
    end

  end

  def self.upvote(suggestion_id)
    suggestion = Suggestion.find(suggestion_id)
    suggestion.update_attribute(:votes, suggestion.votes + 1)
    
    VotingChangedJob.perform_later(@campaign.id)
  end


  def self.unvote(suggestion_id)
    suggestion = @campaing.suggestions.find(suggestion_id)
    suggestion.update_attribute(:votes, suggestion.votes - 1)

    VotingChangedJob.perform_later(@campaign.id)
  end

  def new
    @suggestion = Suggestion.new(campaign_id: @campaign)
    @suggestions = @campaign.suggestions.approved_not_archived
    @random_nickname = Nickname.random()
    @client_id = Digest::SHA1.hexdigest("some-random-string")[8..16]
  end

  def approve
    suggestion = @campaign.suggestions.find(approve_params[:suggestion_id])

    suggestion.approve
    suggestion.save()

    @selected_tab = params[:tab]

    rank = @campaign.suggestions.approved_not_archived.count

    ApprovedSuggestionJob.perform_later(@campaign.id, rank, suggestion.id)

    redirect_to campaign_moderate_path(@campaign, {:tab => @selected_tab})
  end

  def reject
    suggestion = Suggestion.find(params[:suggestion_id])

    suggestion.reject
    suggestion.save()

    @selected_tab = params[:tab]


    RejectedSuggestionJob.perform_later(@campaign.id, suggestion.id)

    redirect_to campaign_moderate_path(@campaign, {:tab => @selected_tab})
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:suggestion, :suggestion_id, :tab, :campaign_id)
  end

  def approve_params
    params.permit(:suggestion_id, :tab, :campaign_id)
  end

  def campaign_suggestion_params
      params.permit(:campaign_id)
  end

  def get_campaign
    @campaign = Campaign.find(campaign_suggestion_params[:campaign_id])
  end

end

app/helpers/suggestion_helper.rb
module SuggestionHelper
end

app/views/suggestion/_single_suggestion.html.haml
%div.row.suggestion-row{ "suggestion-id" => "#{suggestion.id}", "data-votes" => suggestion.votes, "data-updated" => suggestion.updated_at_as_integer}
  %div.col-xs-12
    %div.col-xs-1
      %span.pull-left
        %h4.rank{ :id => "suggestion_#{suggestion.id}_rank"}
          #{rank}
    %div.col-xs-10
      %span.pull-left
        %h4
          #{suggestion.suggestion}
    %div.col-xs-1
      %span.pull-right
        %h4.number-of-votes{ :id => "suggestion_#{suggestion.id}_votes"}
          #{suggestion.votes}

app/views/suggestion/_suggestion.html.haml
- rank = suggestion_counter + 1

%div.row.suggestion-row{ "suggestion-id" => "#{suggestion.id}", "data-votes" => suggestion.votes, "data-updated" => suggestion.updated_at_as_integer}
  %div.col-xs-12
    %div.col-xs-1
      %span.pull-left
        %h4.rank{ :id => "suggestion_#{suggestion.id}_rank"}
          #{rank}
    %div.col-xs-10
      %span.pull-left
        %h4
          #{suggestion.suggestion}
    %div.col-xs-1
      %span.pull-right
        %h4.number-of-votes{ :id => "suggestion_#{suggestion.id}_votes"}
          #{suggestion.votes}

app/views/suggestion/_suggestion_form.html.haml
%nav.navbar.navbar-default.navbar-fixed-bottom.voting-footer{ :style => "display:"}

  = form_for @suggestion, url: campaign_suggestion_index_url(@suggestion, campaign_id: @campaign.id), remote: true, html: { class: 'horizontal-form' } do |f|
    .form-group
      .col-xs-10
        = f.text_field :suggestion, class: 'form-control', placeholder: 'SUGGESTION'
      %button.pull-left.col-xs-1.suggestion-submit-button{ id: 'suggestion-submit'}
        %i.fa.fa-paper-plane

%nav.navbar.navbar-default.navbar-fixed-bottom.timeout-footer{ :style => "display:none"}
  .col-xs-12.text-center
    #countdown

app/views/suggestion/new.html.haml
%input{:type =>'hidden', :id => 'voting-page', :value => @campaign.id}

#suggestion_wrapper{:style => "display:none", "campaign-id" => @campaign.id}
  = render partial: 'suggestion/suggestion', collection: @suggestions